apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/markpanizales/argo-combined-app.git
    targetRevision: HEAD
    kustomize:
      images:
      - markpanizales/argo-combined-app:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
